front_end_homepage:
    path:     /
    defaults: { _controller: AndreaCatozziFrontEndBundle:Default:index }

front_end_biography:
    path:     /biography
    defaults: { _controller: AndreaCatozziFrontEndBundle:Default:biography }

front_end_contact:
    path:     /contact
    defaults: { _controller: AndreaCatozziFrontEndBundle:Default:contact }

front_end_pictures:
    path:     /pictures
    defaults: { _controller: AndreaCatozziFrontEndBundle:Default:pictures }

front_end_videos:
    path:     /videos
    defaults: { _controller: AndreaCatozziFrontEndBundle:Default:videos }

back_office_access:
    path:     /admin
    defaults: { _controller: AndreaCatozziBackOfficeBundle:Default:index }