andrea_catozzi_back_office:
    resource: "@AndreaCatozziBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /

andrea_catozzi_front_end:
    resource: "@AndreaCatozziFrontEndBundle/Resources/config/routing.yml"
    prefix:   /

andrea_catozzi_user:
    resource: "@AndreaCatozziUserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: AndreaCatozziBackOfficeBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

pictures:
    resource: "@AndreaCatozziBackOfficeBundle/Controller/Media/PictureController.php"
    type:     annotation