back_office_homepage:
    path:     /admin
    defaults: { _controller: AndreaCatozziBackOfficeBundle:Default:index }

back_office_biography:
    path:     /admin/biography
    defaults: { _controller: AndreaCatozziBackOfficeBundle:Default:biography }

back_office_contact:
    path:     /admin/contact
    defaults: { _controller: AndreaCatozziBackOfficeBundle:Default:contact }

back_office_videos:
    path:     /admin/videos
    defaults: { _controller: AndreaCatozziBackOfficeBundle:Default:videos }

login:
    path:     /login
    defaults: { _controller: AndreaCatozziBackOfficeBundle:Default:login }